### ISSUE TITLE
tunsafe默认安装在Program Files 可如此处理空格

### ISSUE THREAD

**Issue by lewoking** [lmc999/auto-add-routes#11]
修改为如下格式
PreUp = start "" "C:\Program Files\TunSafe\QOS\routes-up.bat"
PostDown = start "" "C:\Program Files\TunSafe\QOS\routes-down.bat"

**Comment by yduke** [comment]
感谢

**Comment by hewittchoi** [comment]
> 感谢

把route文件夹加压在没有空格的文件也是可以的

**Comment by zjy7** [comment]
感谢

**Comment by dddddassas** [comment]
感谢，可用

**Comment by Hugh-Zhu** [comment]
也可以用Windows的“~”处理，比如：
`C:\Program Files\TunSafe\QOS\routes-up.bat` 改为 `C:\Progra~1\TunSafe\QOS\routes-up.bat`

**Comment by MOBIUSLINK** [comment]
> 也可以用Windows的“~”处理，比如：
> `C:\Program Files\TunSafe\QOS\routes-up.bat` 改为 `C:\Progra~1\TunSafe\QOS\routes-up.bat`

此方法不可行，不建议浪费一次重启的时间尝试
