### ISSUE TITLE
启用了Overture似乎不能做到分流作用

### ISSUE THREAD

**Issue by StudenGit** [lmc999/auto-add-routes#14]
具体是这样的，我没有用WG或者openVNP，用的是其他的全局VPN
我在windows上，把WG文件夹里的route.zip解压，运行里面的route-up.bat，

![Snipaste_2020-03-21_11-25-10](https://user-images.githubusercontent.com/33886886/77218487-ad817480-6b66-11ea-9ab6-6fa3a8370b2e.png)

然后用route print查询，路由表确实写进去了
![Snipaste_2020-03-21_11-24-02](https://user-images.githubusercontent.com/33886886/77218477-8a56c500-6b66-11ea-8ae9-645c7d2f9e97.png)

然后再运行dns-up.bat，连接上VPN，之后用ip111.cn查询没问题：
![Snipaste_2020-03-21_11-26-39](https://user-images.githubusercontent.com/33886886/77218504-e0c40380-6b66-11ea-93c4-ee6ba56a370d.png)

但是仍然是打不开baidu.com，Overture似乎没起到作用
我感觉似乎是这儿出了问题：

> ExcludedIPs = 127.0.0.1/32
> 然后修改配置文件的DNS地址为本机地址即：127.0.0.1

但是即使我修改了DNS地址好像还是不行
除了baidu.com，其他的163.com，youku.com都打不开

请问这是怎么回事？

**Comment by StudenGit** [comment]
PS：修改了跃点数还是不行

![Snipaste_2020-03-21_11-52-29](https://user-images.githubusercontent.com/33886886/77218823-7614c700-6b6a-11ea-9aba-97f645484bbb.png)

**Comment by lmc999** [comment]
在route目录运行overture-windows-amd64.exe有什么输出？
