### ISSUE TITLE
启动 cmroute.dll 时出现问题 找不到指定模块

### ISSUE THREAD

**Issue by dazhangg** [lmc999/auto-add-routes#15]
启动 cmroute.dll 时出现问题 找不到指定模块,这个时什么原因啊。

**Comment by lmc999** [comment]
你把dll拷贝到C:\Windows\System32试试

**Comment by dazhangg** [comment]
> 你把dll拷贝到C：\ Windows \ System32试试

谢谢，我最近更新了系统补丁，使用中发现并没有报错了，并且路由条目已经在路由表中添加。
