### ISSUE TITLE
配置之后链接谷歌提示：“您的连接不是私密连接”

### ISSUE THREAD

**Issue by crescenth** [lmc999/auto-add-routes#16]
www.google.com 通常会使用加密技术来保护您的信息。Google Chrome 此次尝试连接到 www.google.com 时，此网站发回了异常的错误凭据。这可能是因为有攻击者在试图冒充 www.google.com，或 Wi-Fi 登录屏幕中断了此次连接。请放心，您的信息仍然是安全的，因为 Google Chrome 尚未进行任何数据交换便停止了连接。

您目前无法访问 www.google.com，因为此网站使用了 HSTS。网络错误和攻击通常是暂时的，因此，此网页稍后可能会恢复正常。

**Comment by crescenth** [comment]
chrome 浏览器

**Comment by lmc999** [comment]
是否改动过overture的设置？

**Comment by realaaaaa** [comment]
这几天出现的问题，google facebook等站点解析后，会认为是国内站点，导致直连失败

**Comment by lmc999** [comment]
> 这几天出现的问题，google facebook等站点解析后，会认为是国内站点，导致直连失败
> 直接不使用分流策略是能正常访问

把出现问题的域名添加到domain_alternative_sample，指定用默认设置中的OpenDNS解析。

**Comment by realaaaaa** [comment]
> > 这几天出现的问题，google facebook等站点解析后，会认为是国内站点，导致直连失败
> > 直接不使用分流策略是能正常访问
> 
> 把出现问题的域名添加到domain_alternative_sample，指定用默认设置中的OpenDNS解析。

谢谢，刚才检查了下，我们默认配置就已经包含了他们，现在google facebook间歇性抽风，不分流正常，可能解析到的IP时候会是anycast的IP，被ip库识别成国内ip了。
