### ISSUE TITLE
国内网站正常分流，国外的可以打开YouTube网页，不过无法观看YouTube视频，还无法打开Google网页，facebook网页，Twitter网页

### ISSUE THREAD

**Issue by 1353604736** [lmc999/auto-add-routes#19]
也无法访问Google网页，facebook网页，Twitter网页 这些被抢网站

**Comment by lmc999** [comment]
考虑默认设置中的OpenDNS被劫持，可尝试使用DoH协议的DNS解析境外网站
修改overture配置文件config.json的AlternativeDNS：

  "AlternativeDNS": [
    {
      "Name": "CloudFlare",
      "Address": "https://cloudflare-dns.com/dns-query",
      "Protocol": "https",
      "SOCKS5Address": "",
      "Timeout": 6,
      "EDNSClientSubnet": {
        "Policy": "disable",
        "ExternalIP": "",
        "NoCookie": true
      }
    }

**Comment by 1353604736** [comment]
![2020-10-20 18-47-20](https://user-images.githubusercontent.com/12869582/96576559-ef44ea00-1304-11eb-90b1-20ae5d911eb6.png)
![2020-10-20 18-46-32](https://user-images.githubusercontent.com/12869582/96576567-f10ead80-1304-11eb-9bf8-7cc91180b7e7.png)
不知道这算不算是成功了，感觉一直在用openvpn访问国内，访问淘宝首页跳转到了world.taobao.com，国内v.qq.com，youku.com，bilibili.com都加载特慢，YT,FB,TR正常访问

> 考虑到默认设置中的OpenDNS被劫持，可尝试使用DoH协议的DNS解析环境外部网站
> 修改配置文件config.json的替代DNS ：
> 
> “ AlternativeDNS”：[
> {
> “名称”：“ CloudFlare”，
> “地址”：“ https://cloudflare-dns.com/dns-query”，
> “协议”：“ https”，
> “ SOCKS5Address”：“”，
> “超时”：6，
> “ EDNSClientSubnet”：{
> “策略”：“禁用”，
> “ ExternalIP”：“”，
> “ NoCookie”：true
> }
> }

**Comment by lmc999** [comment]
你可以在电脑用besttrace看一下到以上网址的路由是怎么走的，是不是经过你的VPN代理了
