### ISSUE TITLE
当虚拟网卡的优先级高于真实网卡时，添加的路由表都指向了虚拟网卡

### ISSUE THREAD

**Issue by xtiter** [lmc999/auto-add-routes#2]
当tunsafe连接后，出现虚拟网卡的跃点数低于真实网卡的跃点数，勾选pre后执行bat后新增路由表的指向都是虚拟网卡，IP分流没有起效，是否能加入判断处理这种情况？

![image](https://user-images.githubusercontent.com/25069631/48383442-b5ced180-e720-11e8-84db-1794c689160d.png)

![image](https://user-images.githubusercontent.com/25069631/48383551-27a71b00-e721-11e8-9a75-831ea98ea82d.png)

**Comment by InoriHimea** [comment]
@lmc999 怎么我一改，路由表就加不进去了
add 1.0.1.0 mask 255.255.255.0 192.168.1.1 METRIC 20 IF default
![default](https://user-images.githubusercontent.com/33611921/48393571-1d017b80-e74b-11e8-98ca-833adea8650d.PNG)

**Comment by ltitman** [comment]
直接修改网关，添加的路由表的接口和跃点数依旧是虚拟网卡的，如果修改接口或是跃点数，bat脚本直接闪退，路由表无法添加。

**Comment by lmc999** [comment]
> @lmc999 怎么我一改，路由表就加不进去了
> add 1.0.1.0 mask 255.255.255.0 192.168.1.1 METRIC 20 IF default
> ![default](https://user-images.githubusercontent.com/33611921/48393571-1d017b80-e74b-11e8-98ca-833adea8650d.PNG)

按图片这样来改，跃点数可以不改
![qq 20181113150251](https://user-images.githubusercontent.com/39726914/48396478-85555a80-e755-11e8-939e-cbd460493362.jpg)

**Comment by lmc999** [comment]
> 直接修改网关，添加的路由表的接口和跃点数依旧是虚拟网卡的，如果修改接口或是跃点数，bat脚本直接闪退，路由表无法添加。

你是在add.txt和del.txt上面修改的吧？

**Comment by ltitman** [comment]
> > 直接修改网关，添加的路由表的接口和跃点数依旧是虚拟网卡的，如果修改接口或是跃点数，bat脚本直接闪退，路由表无法添加。
> 
> 你是在add.txt和del.txt上面修改的吧？

是的。

**Comment by lmc999** [comment]
> > > 直接修改网关，添加的路由表的接口和跃点数依旧是虚拟网卡的，如果修改接口或是跃点数，bat脚本直接闪退，路由表无法添加。
> > 
> > 
> > 你是在add.txt和del.txt上面修改的吧？
> 
> 是的。

按我上图修改试试，我试过可以正常添加和删除路由

**Comment by lmc999** [comment]
> > > > > 直接修改网关，添加的路由表的接口和跃点数依旧是虚拟网卡的，如果修改接口或是跃点数，bat脚本直接闪退，路由表无法添加。
> > > > 
> > > > 
> > > > 你是在add.txt和del.txt上面修改的吧？
> > > 
> > > 
> > > 是的。
> > 
> > 
> > 按我上图修改试试，我试过可以正常添加和删除路由
> 
> 还是不行，接口和跃点数不对，分流失败

你试试手动修改网卡跃点数吧，再不行只能留这个issue在这里看看有没有其他人可以jiejuenidewenti
https://www.windows10.pro/set-netipinterface-interfaceindex-interfacemetric/

**Comment by ltitman** [comment]
> > > > > > 直接修改网关，添加的路由表的接口和跃点数依旧是虚拟网卡的，如果修改接口或是跃点数，bat脚本直接闪退，路由表无法添加。
> > > > > 
> > > > > 
> > > > > 你是在add.txt和del.txt上面修改的吧？
> > > > 
> > > > 
> > > > 是的。
> > > 
> > > 
> > > 按我上图修改试试，我试过可以正常添加和删除路由
> > 
> > 
> > 还是不行，接口和跃点数不对，分流失败
> 
> 你试试手动修改网卡跃点数吧，再不行只能留这个issue在这里看看有没有其他人可以解决你的问题
> https://www.windows10.pro/set-netipinterface-interfaceindex-interfacemetric/

这个方法行得通，thanks！

**Comment by libsgh** [comment]
> > > > > > > 直接修改网关，添加的路由表的接口和跃点数依旧是虚拟网卡的，如果修改接口或是跃点数，bat脚本直接闪退，路由表无法添加。
> > > > > > 
> > > > > > 
> > > > > > 你是在add.txt和del.txt上面修改的吧？
> > > > > 
> > > > > 
> > > > > 是的。
> > > > 
> > > > 
> > > > 按我上图修改试试，我试过可以正常添加和删除路由
> > > 
> > > 
> > > 还是不行，接口和跃点数不对，分流失败
> > 
> > 
> > 你试试手动修改网卡跃点数吧，再不行只能留这个issue在这里看看有没有其他人可以解决你的问题
> > https://www.windows10.pro/set-netipinterface-interfaceindex-interfacemetric/
> 
> 这个方法行得通，thanks！

我修改了真实网卡点数为10，虚拟网卡为20，分流还是失败啊

**Comment by lmc999** [comment]
> 我修改了真实网卡点数为10，虚拟网卡为20，分流还是失败啊，重启tunsafe后，虚拟的网卡会自动重置成2
你是安装了sstap的虚拟网卡吗？是的话删了重新安装虚拟网卡，不要安装sstap自带的。

**Comment by libsgh** [comment]
![image](https://user-images.githubusercontent.com/25656088/49553750-2d64da80-f934-11e8-9a92-7d289d53d941.png)
不清楚你说的sstap是什么，我只有两个网卡其中一个是安装tunsafe后自带的，是删除这个重新安装吗？如果是，如何重新安装呢？

**Comment by lmc999** [comment]
> ![image](https://user-images.githubusercontent.com/25656088/49553750-2d64da80-f934-11e8-9a92-7d289d53d941.png)
> 不清楚你说的sstap是什么，我只有两个网卡其中一个是安装tunsafe后自带的，是删除这个重新安装吗？如果是，如何重新安装呢？

建议你百度...

**Comment by libsgh** [comment]
> > ![image](https://user-images.githubusercontent.com/25656088/49553750-2d64da80-f934-11e8-9a92-7d289d53d941.png)
> > 不清楚你说的sstap是什么，我只有两个网卡其中一个是安装tunsafe后自带的，是删除这个重新安装吗？如果是，如何重新安装呢？
> 
> 建议你百度如何重装虚拟网卡...

这个虚拟网卡是tunsafe安装的时候自动装的，每次启动tunsafe，点数就变了

**Comment by qiang2000** [comment]
> 当tunsafe连接后，出现虚拟网卡的跃点数低于真实网卡的跃点数，勾选pre后执行bat后新增路由表的指向都是虚拟网卡，IP分流没有起效，是否能加入判断处理这种情况？
> 
> ![image](https://user-images.githubusercontent.com/25069631/48383442-b5ced180-e720-11e8-84db-1794c689160d.png)
> 
> ![image](https://user-images.githubusercontent.com/25069631/48383551-27a71b00-e721-11e8-9a75-831ea98ea82d.png)



> > > > > 直接修改网关，添加的路由表的接口和跃点数依旧是虚拟网卡的，如果修改接口或是跃点数，bat脚本直接闪退，路由表无法添加。
> > > > 
> > > > 
> > > > 你是在add.txt和del.txt上面修改的吧？
> > > 
> > > 
> > > 是的。
> > 
> > 
> > 按我上图修改试试，我试过可以正常添加和删除路由
> 
> 还是不行，接口和跃点数不对，分流失败
> ![image](https://user-images.githubusercontent.com/25069631/48397264-2e04b980-e758-11e8-9d14-431c4128dd8c.png)
> ![image](https://user-images.githubusercontent.com/25069631/48397326-4b398800-e758-11e8-9334-e6fde0241cb0.png)



> > > > > 直接修改网关，添加的路由表的接口和跃点数依旧是虚拟网卡的，如果修改接口或是跃点数，bat脚本直接闪退，路由表无法添加。
> > > > 
> > > > 
> > > > 你是在add.txt和del.txt上面修改的吧？
> > > 
> > > 
> > > 是的。
> > 
> > 
> > 按我上图修改试试，我试过可以正常添加和删除路由
> 
> 还是不行，接口和跃点数不对，分流失败
> ![image](https://user-images.githubusercontent.com/25069631/48397264-2e04b980-e758-11e8-9d14-431c4128dd8c.png)
> ![image](https://user-images.githubusercontent.com/25069631/48397326-4b398800-e758-11e8-9334-e6fde0241cb0.png)

终极解决方案！！！
正确修改add.txt 和 del.txt。
![image](https://user-images.githubusercontent.com/44046811/51087439-5461c800-178e-11e9-9c66-3835ed1aae44.png)
route print  查看你真实网卡的ID，修改add,txt和del.txt.
![image](https://user-images.githubusercontent.com/44046811/51087485-000b1800-178f-11e9-950b-451dc99c8956.png)
修改网关
![image](https://user-images.githubusercontent.com/44046811/51087521-609a5500-178f-11e9-8b0e-0c2d2f81c36d.png)
按上述方法修改，再看效果。
![image](https://user-images.githubusercontent.com/44046811/51087536-9b03f200-178f-11e9-8d57-e824afefec73.png)

**Comment by fongfai** [comment]
> > > ![image](https://user-images.githubusercontent.com/25656088/49553750-2d64da80-f934-11e8-9a92-7d289d53d941.png)
> > > 不清楚你说的sstap是什么，我只有两个网卡其中一个是安装tunsafe后自带的，是删除这个重新安装吗？如果是，如何重新安装呢？
> > 
> > 
> > 建议你百度如何重装虚拟网卡...
> 
> 这个虚拟网卡是tunsafe安装的时候自动装的，每次启动tunsafe，点数就变了

和你同样的问题...
