### ISSUE TITLE
修复一下吧，谷歌和油管解析确实有问题

### ISSUE THREAD

**Issue by luowei729** [lmc999/auto-add-routes#21]
可以确定本地设置没问题

**Comment by luowei729** [comment]
找到问题了，确实更新下add.txt和得了del.txt就可以了，作者要wiki上说明一下让跟新

**Comment by lmc999** [comment]
https://github.com/lmc999/auto-add-routes/issues/19#issuecomment-712156485

**Comment by luowei729** [comment]
> [#19 (comment)](https://github.com/lmc999/auto-add-routes/issues/19#issuecomment-712156485)

按照改过了，还是打不开谷歌和油管视频

**Comment by luowei729** [comment]
> [#19 (comment)](https://github.com/lmc999/auto-add-routes/issues/19#issuecomment-712156485)

按照改了，问题依旧

**Comment by luowei729** [comment]
> [#19 (comment)](https://github.com/lmc999/auto-add-routes/issues/19#issuecomment-712156485)

我知道什么问题了，这种实现是有问题的，名单内的域名会默认用本机网卡解析，也就是用路由器192.168.1.1去解析，当然解析不到正确的。如果192.168.1.1路由器上面部署了分流DNS，就没有这个问题了。还是实现方案的问题。由此想到一个思路，用虚拟网卡做默认网卡配置127.0.0.1去解析，发现是大陆的IP，再分流到本机网卡，这样应该可以

**Comment by luowei729** [comment]
> [#19 (comment)](https://github.com/lmc999/auto-add-routes/issues/19#issuecomment-712156485)

我知道什么问题了，这种实现是有问题的，名单内的域名会默认用本机网卡解析，也就是用路由器192.168.1.1去解析，当然解析不到正确的。如果192.168.1.1路由器上面部署了分流DNS，就没有这个问题了。还是实现方案的问题。由此想到一个思路，用虚拟网卡做默认网卡配置127.0.0.1去解析，发现是大陆的IP，再分流到本机网卡，这样应该可以

**Comment by lmc999** [comment]
没有理解错的话，就是说你的路由器上的DNS服务器劫持了局域网内的设备的DNS解析结果对吧？那这种情况当然无法正常访问谷歌和油管

**Comment by luowei729** [comment]
> 没有理解错的话，就是说你的路由器上的DNS服务器劫持了局域网内的设备的DNS解析结果对吧？那这种情况当然无法正常访问谷歌和油管

不是，直接127.0.0.1怎么可能被网关劫持，应该是实现问题

**Comment by luowei729** [comment]
> 没有理解错的话，就是说你的路由器上的DNS服务器劫持了局域网内的设备的DNS解析结果对吧？那这种情况当然无法正常访问谷歌和油管

目前的实现思路错了，要把虚拟网卡做默认网卡，虚拟网卡配置127.0.0.1做DNS，解析到大陆IP再分流到本机物理网卡，你这样实现实试试，还有，虚拟网卡生成只能是100M带宽的么
