### ISSUE TITLE
您好，请教一个chnrouer更新和转换的问题。

### ISSUE THREAD

**Issue by jake2003a** [lmc999/auto-add-routes#38]
china CIDR 目前最新的已有8000+,而add里的才6000+，请问如何把最新的文本CIDR(例如一行是16.0.5.0/28)转换成add路由文本的形式？
数千行的CIDR，总不能手动转换吧？还请不吝赐教。

**Comment by lmc999** [comment]
最简单的方法就是用word/WPS的查找和替换功能
