### ISSUE TITLE
添加配置的代码

### ISSUE THREAD

**Issue by lnzhao1** [lmc999/auto-add-routes#4]
你好，我在win7环境下添加config里的两行配置要写成
PreUp = start "" "D:\Program Files\TunSafe\auto-add-routes-master\routes-up.bat"
PostDown = start "" "D:\Program Files\TunSafe\auto-add-routes-master\routes-down.bat"
才管用（双引号很重要，没有不好使）；

**Comment by lmc999** [comment]
因为你的文件路径有空格了，用默认方法路径不能有空格
