### ISSUE TITLE
macos可解？

### ISSUE THREAD

**Issue by huyuanjun976** [lmc999/auto-add-routes#43]
什么时候可以出macos版本？

**Comment by klacee** [comment]
能否出个wg0.conf文件
类似这种的，我是是在不懂，搞不了最新版的
PRIORITY=${PRIORITY:-1024}
ip -4 rule add to 172.67.166.20/32 priority ${PRIORITY}
ip -4 rule add to 104.21.16.37/32 priority ${PRIORITY}
ip -6 rule add to 2606:4700:3036::ac43:a614/128 priority ${PRIORITY}
ip -6 rule add to 2606:4700:3030::6815:1025/128 priority ${PRIORITY}
#ip -4 rule add to 1.1.1.1 priority ${PRIORITY}
#ip -4 rule add to 1.0.0.1 priority ${PRIORITY}
#ip -4 rule add to 8.8.8.8 priority ${PRIORITY}
#ip -4 rule add to 8.8.4.4 priority ${PRIORITY}
#ip -4 rule add to 9.9.9.9 priority ${PRIORITY}
#ip -4 rule add to 149.112.112.112 priority ${PRIORITY}
ip -6 rule add to 2606:4700:4700::/64 priority ${PRIORITY}
ip -4 rule add to 0.0.0.0/8 priority ${PRIORITY}
ip -4 rule add to 10.0.0.0/8 priority ${PRIORITY}
ip -4 rule add to 100.64.0.0/10 priority ${PRIORITY}
ip -4 rule add to 169.254.0.0/16 priority ${PRIORITY}
ip -4 rule add to 172.16.0.0/12 priority ${PRIORITY}
ip -4 rule add to 192.168.0.0/17 priority ${PRIORITY}
ip -4 rule add to 198.18.0.0/15 priority ${PRIORITY}
ip -4 rule add to 224.0.0.0/4 priority ${PRIORITY}
ip -4 rule add to 255.255.255.255/32 priority ${PRIORITY}

**Comment by lmc999** [comment]
没有支持macos的打算，可以尝试其他支持wireguard的第三方代理工具例如sing-box, xray之类
