### ISSUE TITLE
请问设置分流后访问国内网站还是明显的卡顿是为何呢?

### ISSUE THREAD

**Issue by just4somefun** [lmc999/auto-add-routes#5]
访问ip111.cn能成功看到被成功分流了

但是打开国内网站的时候,还是明显的卡顿延迟

请问要如何确定国内的流量是否有被误转发

**Comment by lmc999** [comment]
因为你访问的网站有海外节点，当你使用WG时DNS一般默认是8.8.8.8。这是一个海外的DNS，访问有海外节点的网站时会把你解析到海外节点，所以访问慢
