### ISSUE TITLE
不知为何，无法正常分流哔哩哔哩，请问如何手动添加路由？

### ISSUE THREAD

**Issue by RiRiRicardo** [lmc999/auto-add-routes#8]
不知为何，无法正常分流哔哩哔哩，请问如何手动添加路由？

**Comment by lmc999** [comment]
因为你访问的网站有海外节点，当你使用WG时DNS一般默认是8.8.8.8。这是一个海外的DNS，访问有海外节点的网站时会把你解析到海外节点，即是判断你是从大陆以外地区访问，所以无法观看哔哩哔哩的版权视频
